---

- name: Create instance(s)
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:

#  identityProviders:
#  - challenge: true
#    login: true
#    mappingMethod: claim
#    name: allow_all
#    provider:
#      apiVersion: v1
#      kind: HTPasswdPasswordIdentityProvider
#      file: /etc/origin/master/htpasswd

    - name: zeile in master-config.yaml hinzufügen (1)
      lineinfile: dest=master-config.yaml regexp="^\ \ \ \ name\:\ allow_all" line="    name{{':'}} htpasswd_provider"

    - name: zeile in master-config.yaml hinzufügen (2)
      lineinfile: dest=master-config.yaml regexp="^      kind\:\ AllowAllIdentityProvider" line="      kind{{':'}} HTPasswdPasswordIdentityProvider\n      file{{':'}} /etc/origin/master/htpasswd"

