- name: Create storage account
  azure_rm_storageaccount:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_storage_account_name }}
    account_type: Standard_LRS

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_virtual_network_name }}
    address_prefixes: "10.10.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_virtual_sub_network_name }}
    address_prefix: "10.10.0.0/24"
    virtual_network: {{ azure_virtual_network_name }}

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: {{ azure_resource_group }}
    allocation_method: Static
    name: {{ azure_public_ip_name }}

- name: Create security group that allows SSH
    azure_rm_securitygroup:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_security_group_name }}
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

- name: Create NIC
  azure_rm_networkinterface:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_nic_name }}
    virtual_network: {{ azure_virtual_network_name }}
    subnet: {{ azure_virtual_sub_network_name }}
    public_ip_name: {{ azure_public_ip_name }}
    security_group: {{ azure_security_group_name }}

- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: {{ azure_resource_group }}
    name: {{ azure_vm_name }}
    vm_size: {{ azure_vm_size }}
    storage_account: {{ azure_storage_account_name }}
    storage_container: {{ azure_vm_name }}
    storage_blob: {{ azure_vm_name }}.vhd
    admin_username: {{ azure_user_name }}
    ssh_password: false
    ssh_public_keys: "{{ azure_ssh_keys }}"
    network_interfaces: testnic001
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
