---
# (ami-6d1c2007) centos 7 - us-east-1
# (ami-af4333cf) centos 8 - us-west-1

# Anlage der Security Group
- name: example ec2 group
  ec2_group:
    name: tm-security-group
    description: Group for TicketMonster Example
#    vpc_id: 12345
    region: "us-west-1"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ myip.stdout }}/32"
      - proto: tcp
        from_port: 9999
        to_port: 9999
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

# VM deployen
- name: Provision a set of instances
  ec2:
    group: tm-security-group
    key_name: "{{ ssh_key_name }}"
    instance_type: t2.micro
    image: "ami-af4333cf"
    wait: true
    region: "us-west-1"
    count: "{{ instances | length }}"
    instance_tags:
      group: "{{ instance_type }}"
  register: ec2

- name: add Name tag to instances
  ec2_tag: resource={{ item.1.id }} region="us-west-1" state=present
  with_together:
    - instances
    - ec2.instances
  args: 
    tags:
      Name: "{{ item.0 }}"

- name: Wait for ssh
  wait_for: "port=22 host={{ item.dns_name }}"
  with_items: ec2.instances

- name: Wait for user setup
  command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null {{ ansible_ssh_user }}@{{ item.1.dns_name }} echo {{ ansible_ssh_user }} user is setup"
  register: result
  until: result.rc == 0
  retries: 20
  delay: 10
  with_together:
  - instances
  - ec2.instances
