---
# (ami-6d1c2007) centos 7

- name: Provision a set of instances
  ec2:
    group: oo-security-group
    key_name: acer_controller_box
    instance_type: t2.micro
    image: "ami-6d1c2007"
    wait: true
    region: "us-east-1"
    count: "{{ instances | length }}"
    instance_tags:
      group: "{{ instance_type }}"
  register: ec2

- name: add Name tag to instances
  ec2_tag: resource={{ item.1.id }} region="us-east-1" state=present
  with_together:
    - instances
    - ec2.instances
  args: 
    tags:
      Name: "{{ item.0 }}"

- name: Wait for ssh
  wait_for: "port=22 host={{ item.dns_name }}"
  with_items: ec2.instances

- name: Wait for user setup
  command: "ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null {{ ansible_ssh_user }}@{{ item.1.dns_name }} echo {{ ansible_ssh_user }} user is setup"
  register: result
  until: result.rc == 0
  retries: 20
  delay: 10
  with_together:
  - instances
  - ec2.instances
