---

- name: Debug num-Variables 
  hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
 
    - debug: msg="{{ num_dbsrvs }}"

- name: Install DB-Server
  hosts: tag_group_dbsrv

  roles:
    - { role: ticketmonster-dbsrv } 

- name: Install JBoss
  hosts: tag_group_appsrv

  roles:
    - { role: ticketmonster-appsrv }

- name: Install Ticketmonster
  hosts: tag_group_devclt

  roles:
    - { role: ticketmonster-devclt }

- name: Install JMeter Client
  hosts: tag_group_jmeterclt

  roles:
    - { role: ticketmonster-jmeterclt }

- name: Install CheckMK Server
  hosts: tag_group_checkmksrv

  roles:
    - { role: ticketmonster-checkmksrv }

