---
- set_fact: instance_type="checkmksrv"

- name: Generate checkmksrv instance names(s)
  set_fact:
    scratch_name: "{{ cluster_id }}-{{ instance_type }}-{{ '%05x' | format(1048576 | random) }}"
  register: checkmksrv_names_output
  with_sequence: count={{ num_checkmksrvs }}

- set_fact:
    checkmksrv_names: "{{ checkmksrv_names_output.results | default([]) }}"

