---

- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  become: yes
  become_user: root
  with_items:
   - java-1.7.0-openjdk
   - unzip

- name: Download JMeter
  get_url: url=http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist//jmeter/binaries/apache-jmeter-3.0.zip dest=/opt/apache-jmeter-3.0.zip
  become: yes
  become_user: root

- name: Create Dir
  command: mkdir -p /usr/share/
  become: yes
  become_user: root
 
- name: Extract archive
#  unarchive: src=/opt/apache-jmeter-3.0.zip dest=/usr/share/ copy=no creates=/usr/share/jmeter
# unarchive kann nicht mit Leerzeichen in Dateinamen umgehen
  command: unzip -o /opt/apache-jmeter-3.0.zip -d /usr/share
  become: yes
  become_user: root
 
- name: Rename install directory
  command: chdir=/usr/share /bin/mv apache-jmeter-3.0 jmeter
  become: yes
  become_user: root

- name: chown 
  command: chown {{ ansible_ssh_user }}:users /usr/share/jmeter/
  become: yes
  become_user: root

#- name: Kopieren der jmx-Dateien mit Einsetzen der URL des JBoss
#  TODO
  
- name: Kopieren der jmx-Dateien f체r query events tests
  template: src=query_events.jmx.j2 dest=/usr/share/jmeter/tests

- name: Kopieren der jmx-Dateien f체r book tickets tests
  template: src=book_tickets.jmx.j2 dest=/usr/share/jmeter/tests

#- name: Ausf체hren des Tests - dies sp채ter separat
#  TODO
