---

- name: Add repo file
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644
  become: True
  become_user: root

- name: Install MariaDB
  yum: name={{ item }} enablerepo=mariadb state=present
  become: True
  become_user: root
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Install MySQLdb Python package for secure installations.
  yum: name=MySQL-python state=present
  become: True
  become_user: root
#  when: mysql_secure_installation and mysql_root_password is defined

- name: Add configuration
  template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir }}/{{ mysql_conf_file }} owner=root group=root mode=0644
#  when: mysql_conf_tpl != 'change_me'
  become: True
  become_user: root
  notify: restart mysql

- name: Start and enable service
  become: True
  become_user: root
  service: name=mysql state=started enabled=yes

- name: Anlage einer Datenbank für Ticketmonster
  mysql_db: name=ticketmonster state=present login_user=root login_password={{ mysql_root_password }}

- name: Anlage Nutzer 
  mysql_user: name=ticketmonster password=ticketmonster priv=*.* state=present login_user=root login_password={{ mysql_root_password }}
