- name: install packages
  yum: name={{ item }} state=installed
  become: yes
  become_user: root
  with_items:
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - httpd-tools
    
- name: download maven
  tags: maven
  include: ../../silpion.lib/tasks/get_url.yml
  vars:
    url: "{{ maven_mirror }}/{{ maven_redis_filename }}"
    filename: "{{ maven_redis_filename }}"

- name: Upload installation archive
  tags: maven
  include: ../../silpion.lib/tasks/copy.yml
  vars:
    filename: "{{ maven_redis_filename }}"

- name: Install Maven installation directory
  tags: maven
  become: true
  file:
    state: directory
    owner: 0
    group: 0
    mode: 0755
    dest: "{{ maven_install_dir }}"

- name: Install Maven
  tags: maven
  become: true
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ maven_redis_filename }}"
    dest: "{{ maven_install_dir }}"
    copy: false
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"

- name: Install Maven bin directory
  tags: maven
  become: true
  file:
    state: directory
    owner: 0
    group: 0
    mode: 0755
    dest: "{{ maven_bin_path }}"

- name: Install Maven binary
  tags: maven
  become: true
  file:
    state: link
    force: true
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "{{ maven_bin_path }}/mvn"

