- name: install packages
  yum: name={{ item }} state=installed
  become: yes
  become_user: root
  with_items:
    - java7 
    - git

- name: download maven
  get_url: url=http://apache.openmirror.de/maven/maven-3/{{ maven_version }}/binaries/{{ maven_distr_filename }} dest=/home/{{ ansible_user }}

- name: Install Maven installation directory
  tags: maven
  become: true
  file:
    state: directory
    owner: {{ ansible_user }}
    group: {{ ansible_group }}
    mode: 0755
    dest: "/home/{{ ansible_user}}/{{ maven_install_dir }}"

- name: Install Maven
  tags: maven
  become: true
  unarchive:
    src: "/home/{{ ansible_user }}/{{ maven_distr_filename }}"
    dest: "/home/{{ ansible_user }}/{{ maven_install_dir }}"
    copy: false
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"

- name: Install Maven bin directory
  tags: maven
  become: true
  file:
    state: directory
    owner: {{ ansible_user }}
    group: {{ ansible_group }}
    mode: 0755
    dest: "{{ maven_bin_path }}"

- name: Install Maven binary
  tags: maven
  become: true
  file:
    state: link
    force: true
    src: "/home/{{ ansible_user }}/{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "{{ maven_bin_path }}/mvn"

- name: Install workspace directory
  tags: maven
  become: true
  file:
    state: directory
    owner: {{ ansible_user }}
    group: {{ ansible_group }}
    mode: 0755
    dest: "{{ workspace_dir }}"

- name: clone repo
  git: repo=https://github.com/jboss-developer/ticket-monster.git dest="/home/{{ ansible_user}}/workspace"
