---

- name: Debug num-Variables 
  hosts: localhost
  connection: local
  gather_facts: no

- name: Install DB-Server
  hosts: tag_group_mariadbsrv

  roles:
    - { role: mariadb-perftest-dbserver } 

- name: Install DB-Client
  hosts: tag_group_mariadbclient

  vars:
    maria_db_host_ip: "{{ groups['tag_group_mariadbsrv'][0] }}"

  roles:
    - { role: mariadb-perftest-dbclient }

