---

# 
# TODO: ermittlung der dbsrv-adresse automatisch
# entweder aus dem inventory oder per gcloud mit dem Tag
#

- name: debug vars
  debug: var=maria_db_host_ip

- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  become: yes
  become_user: root
  with_items:
   - java-1.7.0-openjdk
   - unzip

- name: Download JBoss from jboss.org
  get_url: url=http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip dest=/opt/jboss-as-7.1.1.Final.zip
  become: yes
  become_user: root

- name: Extract archive
  unarchive: src=/opt/jboss-as-7.1.1.Final.zip dest=/usr/share/ copy=no creates=/usr/share/jboss-as
#  command: chdir=/usr/share /usr/bin/unzip -q /opt/jboss-as-7.1.1.Final.zip creates=/usr/share/jboss-as
  become: yes
  become_user: root

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as
  become: yes
  become_user: root

#- name: set ip from mariadb host
#  set_fact: maria_db_host_ip = "{{ groups['tag_group_dbsrv'] }}"

#- name: debug group
#  debug: msg="{{ groups['tag_group_dbsrv'] }}"

#- name: debug maria_db_host_ip
#  debug: msg="{{ maria_db_host_ip }}"

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/
  become: yes
  become_user: root
  notify: restart jboss

- name: Add group "jboss"
  group: name=jboss
  become: yes
  become_user: root

- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as
  become: yes
  become_user: root

- name: Change ownership of JBoss installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes
  become: yes
  become_user: root

- name: Copy the init script
  copy: src=jboss-as-standalone.sh dest=/etc/init.d/jboss mode=0755
  become: yes
  become_user: root

- name: Enable JBoss to be started at boot
  service: name=jboss enabled=yes state=started 
  become: yes
  become_user: root

- name: add remote user
  command: chdir=/usr/share/jboss-as bin/add-user.sh --silent=true john remote
  become: yes
  become_user: root
