# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-hostmanager")
  raise 'vagrant-hostmanager plugin is required'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  deployment_type = ENV['OPENSHIFT_DEPLOYMENT_TYPE'] || 'origin'
  num_nodes = (ENV['OPENSHIFT_NUM_NODES'] || 2).to_i

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vbox, override|
    override.vm.box = "centos/7"
    vbox.memory = 1024
    vbox.cpus = 2

    # Enable multiple guest CPUs if available
    vbox.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provider "libvirt" do |libvirt, override|
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.driver = 'kvm'
    case deployment_type
    when "openshift-enterprise"
      override.vm.box = "rhel-7"
    when "atomic-enterprise"
      override.vm.box = "rhel-7"
    when "origin"
      override.vm.box = "centos/7"
      override.vm.box_download_checksum = "b2a9f7421e04e73a5acad6fbaf4e9aba78b5aeabf4230eebacc9942e577c1e05"
      override.vm.box_download_checksum_type = "sha256"
    end
  end

  num_dbsrvs.times do |n|
    node_index = n+1
    config.vm.define "dbsrv_node#{node_index}" do |node|
      node.vm.hostname = "dbsrv-node#{node_index}.example.com"
      node.vm.network :private_network, ip: "192.168.50.#{50 + n}"
    end
  end

  num_appsrvs.times do |n|
    node_index = n+1
    config.vm.define "appsrv_node#{node_index}" do |node|
      node.vm.hostname = "appsrv-node#{node_index}.example.com"
      node.vm.network :private_network, ip: "192.168.50.#{60 + n}"
    end
  end

  num_jmeterclts.times do |n|
    node_index = n+1
    config.vm.define "jmeterclt_node#{node_index}" do |node|
      node.vm.hostname = "jmeterclt-node#{node_index}.example.com"
      node.vm.network :private_network, ip: "192.168.50.#{70 + n}"
    end
  end

  num_checkmksrvs.times do |n|
    node_index = n+1
    config.vm.define "checkmksrv_node#{node_index}" do |node|
      node.vm.hostname = "checkmksrv-node#{node_index}.example.com"
      node.vm.network :private_network, ip: "192.168.50.#{80 + n}"
    end
  end

end


