---
- name: Launch instance(s)
  hosts: localhost
  strategy: debug
  connection: local
  become: no
  gather_facts: no

  tasks:

  # Ermittlung der eigenen IP
  - name: checkmyip
    command: curl http://checkip.amazonaws.com/
    register: myip

  - name: debug myip
    debug: var=myip.stdout

  # mariadb-server
  - include: ../mariadb-performance-test/set_dbsrv_launch_facts.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ dbsrv_names }}"
    when: num_dbsrvs > 0

  # jboss-server
  - include: ../mariadb-performance-test/set_dbsrv_launch_facts.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ dbclient_names }}"     
    when: num_dbclients > 0 

- include: ../mariadb-performance-tests/install.yml
