---

- name: Launch instance(s)
  hosts: localhost
  strategy: debug
  connection: local
  become: no
  gather_facts: no

  vars:
    num_dbsrvs: "{{ lookup('env','num_dbsrvs') }}"
    num_dbclients: "{{ lookup('env','num_dbclients') }}"
    ssh_key_name: "{{ lookup('env','ssh_key_name') }}"
    cluster_id: "{{ lookup('env','cluster_id') }}"
    aws_region: "{{ lookup('env','aws_region') }}"
    server_machine_size: "{{ lookup('env','server_machine_size') }}"
    client_machine_size: "{{ lookup('env','client_machine_size') }}"
 
  tasks:

  # Ermittlung der eigenen IP
  - name: checkmyip
    command: curl http://checkip.amazonaws.com/
    register: myip

  - name: debug myip
    debug: var=myip.stdout

  # mariadb-server
  - include: ../mariadb-performance-test/set_dbsrv_launch_facts.yml
  - include: tasks/mariadb_perftest_launch_instances.yml
    vars:
      instances: "{{ dbsrv_names }}"
    when: num_dbsrvs > 0

  # jboss-server
  - include: ../mariadb-performance-test/set_dbclient_launch_facts.yml
  - include: tasks/mariadb_perftest_launch_instances.yml
    vars:
      instances: "{{ dbclient_names }}"     
    when: num_dbclients > 0 

- include: ../mariadb-performance-test/install.yml
