---

- name: Delete instance(s)
  hosts: localhost
  gather_facts: yes
  connection: local

  vars:
    machine_type: n1-standard-1 # 4 core, 15GB RAM
    image: centos-7
    service_account_email: ansible@bubbly-hope-132123.iam.gserviceaccount.com 
    credentials_file: /home/{{ ansible_user_id }}/.gce-credentials
    project_id: bubbly-hope-132123

  tasks:
  
    - name: Terminate instances
      local_action: 
        module: gce
        state: 'absent'
        instance_names:
          - dbsrv-machine
          

