---

- hosts: l_oo_all_hosts

  tasks:

    - name: install httpd-tools
      yum: name=httpd-tools state=installed

    - name: add directory
      command: htpasswd -cb /etc/origin/master/htpasswd {{ origin_console_user }} {{ origin_console_password }}

#    - name: zeile in master-config.yaml hinzufügen
#      lineinfile: dest=/etc/origin/master/master-config.yaml services regexp="^oauthConfig" insertafter="^claim true" line="HtPasswdProvider\nfile:/etc/origin/master/htpasswd"

#    - name: neustart master
#      restart: name=origin-master.service state=restarted



    
