---

- hosts: tag_host-type-master 

  vars_files:
    - secrets.yml

  tasks:

    - name: install httpd-tools
      yum: name=httpd-tools state=installed

    - name: add directory and htpasswd file
      command: htpasswd -cb /etc/origin/master/htpasswd {{ origin_console_username }} {{ origin_console_password }}
      become: yes
      become_user: root 

#    - name: zeile in master-config.yaml hinzufügen
#      lineinfile: dest=/etc/origin/master/master-config.yaml services regexp="^oauthConfig" insertafter="^claim true" line="HtPasswdProvider\nfile:/etc/origin/master/htpasswd"

#    - name: neustart master
#      restart: name=origin-master.service state=restarted



    
