---

#- name: Install Ticketmonster
#  hosts: dev
#  roles:
#    - ticketmonster-dev-station

- name: Install JBoss
  hosts: appsrv
  roles:
    - ticketmonster-appsrv

#- name: Install DB
#  hosts: dbsrv
#  roles:
#    - ticketmonster-dbsrv